### ISSUE TITLE
Layout folder "" not found!

### ISSUE THREAD

**Issue by skrude61** [a-r-m-i-n/pw_teaser#2]
In Version 6.0.1 (also in 6.0.0) the extension issues an error Layout folder "" not found!
If $this->viewSettings['layoutRootPaths'] is not set, the statement
$layoutRootPaths = $this->viewSettings['layoutRootPaths'] ?? [$this->viewSettings['layoutRootPath'] ?? null];
in Classes/Controller/TeaserController.php sets $layoutRootPaths to [''], not to [null].
I think the handling in 5.0.1 was correct
$layoutRootPaths = $this->viewSettings['layoutRootPaths'] ?: [$this->viewSettings['layoutRootPath'] ?: null];
and should be restored.
Same issue for $partialRootPaths and $templateRootPaths.

**Comment by a-r-m-i-n** [comment]
Hi, thanks for you fix.
The problem with ``?:`` is, that it expects an boolean value.

So, if ``$this->viewSettings['layoutRootPaths']`` is null, PHP 8 will throw errors. That was probably the reason, why I've changed it... But I don't remember in detail.

Can you confirm, that your code also works in PHP 8.x?

**Comment by skrude61** [comment]
I have to correct my comment above. The error 'Layout folder "" not found!' is thrown if $this->viewSettings['layoutRootPath'] == ''.
By using the Null Coalescing Operator, you prevent an error in PHP 8 if $this->viewSettings['layoutRootPaths'] (or $this->viewSettings['layoutRootPath']) is not set at all, not even to null. I don't know if this can happen, but in this case you could prevent the error with
$layoutRootPaths = $this->viewSettings['layoutRootPaths'] ?? [isset($this->viewSettings['layoutRootPath']) && $this->viewSettings['layoutRootPath'] ? $this->viewSettings['layoutRootPath'] : null];

**Comment by a-r-m-i-n** [comment]
I was able to reconstruct the issue. And when you enable warnings, you'll get exceptions because of undefined array key.

However, the solution was easy, just a combination of both approaches :D 

```
$layoutRootPaths = $this->viewSettings['layoutRootPaths'] ?? null ?: [$this->viewSettings['layoutRootPath'] ?? null ?: null];
```
